### ISSUE TITLE
Can we use this for Direct Debit integration?

### ISSUE THREAD

**Issue by chanakaDe** [koona-labs/laravel-fints#1]
Hi @abiturma Thank you so much for this awesome package. I'm going to use this and I have a small question. 
Can we use this for Direct Debit integration?
We are going to use this to save new transactions to the bank after a successful online purchase. 
IF we can do Direct Debit integration, do you have any samples? 

Thank you in advance.

**Comment by abiturma** [comment]
Thanks for your nice words. Unfortunately direct debits are not supported. So far the package provides only reading access to the bank account. If you like, feel free to modify the package or to submit a pull request. Contribution is highly welcome :-)
